"""Oʻqituvchi yuklamasi: (oʻqituvchi, fan, guruh) uchligi

Sinxronizatsiya EPOS'dan aynan shu uchlikni hisoblaydi, lekin uni ikkiga
boʻlib saqlardi — teacher_subject va teacher_group. Ikkovidan uchlikni
tiklab boʻlmaydi: bir oʻqituvchi ikki fandan ikki guruhga dars bersa,
kesishma toʻrtta kombinatsiya beradi va ikkitasi yolgʻon. Bazada 162 ta
fanga bir nechta oʻqituvchi biriktirilgan, yaʼni bu chekka holat emas.

Eski ikkita jadval tegilmaydi: ularga savollarning koʻrinishi, fayl
kutubxonasi va natijalar filtri tayanadi.


Revision ID: 060ef70e266f
Revises: c5f30ab71d92
Create Date: 2026-09-01 11:23:13.475865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '060ef70e266f'
down_revision: Union[str, Sequence[str], None] = 'c5f30ab71d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('load_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semester_type', sa.String(length=32), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'group_id', name='uq_teacher_assignment')
    )
    op.create_index(op.f('ix_teacher_assignments_academic_year_id'), 'teacher_assignments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_group_id'), 'teacher_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_subject_id'), 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_index('uq_teacher_assignments_external_ref', 'teacher_assignments', ['external_source', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_teacher_assignments_external_ref', table_name='teacher_assignments', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_subject_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_group_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_academic_year_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
