"""Audit jurnali

Kim qachon kirgani, chiqqani va muhim harakatlar. Shu paytgacha kirishlar
faqat dastur jurnaliga (Loki) tushardi — ularni ko'rish uchun alohida
tizim kerak edi, nizoli holatda esa «buni kim qildi» degan savolga javob
yo'q edi.

Revision ID: 207e0c71cd8f
Revises: a16646bcc0ed
Create Date: 2026-09-29 05:45:35.541872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207e0c71cd8f'
down_revision: Union[str, Sequence[str], None] = 'a16646bcc0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at_id', 'audit_logs', ['created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_event_created_at', 'audit_logs', ['event', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
