"""Mustaqil ish mavzulari

Fan boʻyicha mustaqil oʻrganiladigan mavzular roʻyxati — sillabusdagi
kabi. Uy vazifasidan farqi: muddat, topshirish va baho yoʻq.

DIQQAT: autogenerate har safar `uq_file_folders_personal` ni oʻchirishni
taklif qiladi (qisman indeks, modeldagi taʼrif bilan solishtirilmaydi).
Bu yerdan ataylab olib tashlangan — usiz har foydalanuvchida bittadan
shaxsiy papka boʻlishi kafolati yoʻqolardi.

Revision ID: 3a5c449578cf
Revises: 8fb9acdf3e2a
Create Date: 2026-10-01 12:49:14.551188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5c449578cf'
down_revision: Union[str, Sequence[str], None] = '8fb9acdf3e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_independent_topics',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_independent_topics_course_id'), 'course_independent_topics', ['course_id'], unique=False)
    op.create_index('ix_course_independent_topics_course_position', 'course_independent_topics', ['course_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_independent_topics_course_position', table_name='course_independent_topics')
    op.drop_index(op.f('ix_course_independent_topics_course_id'), table_name='course_independent_topics')
    op.drop_table('course_independent_topics')
    # ### end Alembic commands ###
