"""add_lesson_attendances

Revision ID: 3a783861a927
Revises: 1c6c6dd7f748
Create Date: 2026-09-03 05:46:46.996270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a783861a927'
down_revision: Union[str, Sequence[str], None] = '1c6c6dd7f748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_attendances',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('marked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'student_id', name='uq_lesson_attendance')
    )
    op.create_index(op.f('ix_lesson_attendances_group_id'), 'lesson_attendances', ['group_id'], unique=False)
    op.create_index(op.f('ix_lesson_attendances_lesson_id'), 'lesson_attendances', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_attendances_status'), 'lesson_attendances', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_attendances_student_id'), 'lesson_attendances', ['student_id'], unique=False)
    op.create_index('ix_lesson_attendances_student_lesson', 'lesson_attendances', ['student_id', 'lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_attendances_student_lesson', table_name='lesson_attendances')
    op.drop_index(op.f('ix_lesson_attendances_student_id'), table_name='lesson_attendances')
    op.drop_index(op.f('ix_lesson_attendances_status'), table_name='lesson_attendances')
    op.drop_index(op.f('ix_lesson_attendances_lesson_id'), table_name='lesson_attendances')
    op.drop_index(op.f('ix_lesson_attendances_group_id'), table_name='lesson_attendances')
    op.drop_table('lesson_attendances')
    # ### end Alembic commands ###
