"""Fayl kutubxonasi jadvallari

Yuklangan fayllar uchun markaziy reyestr. Toʻrtta jadval:

* ``file_blobs``  — diskdagi baytlar, sha256 boʻyicha yagona (dublikat yoʻq);
* ``files``       — kutubxona yozuvi: kimniki, qanday nomlangan;
* ``file_folders``— oʻqituvchining shaxsiy tartibi;
* ``file_usages`` — fayl qayerda ishlatilyapti (xavfsiz oʻchirish uchun).

Mavjud jadvallarga tegilmaydi: ``resources.file_url`` va JSONB roʻyxatlar
oʻz joyida qoladi, ular keyingi bosqichda koʻchiriladi.

Revision ID: 4658ab2130d2
Revises: b7d41e0c92aa
Create Date: 2026-08-29 04:13:16.904335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4658ab2130d2'
down_revision: Union[str, Sequence[str], None] = 'b7d41e0c92aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_blobs_sha256'), 'file_blobs', ['sha256'], unique=True)
    op.create_table('file_folders',
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['file_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_folders_owner_user_id'), 'file_folders', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_file_folders_parent_id'), 'file_folders', ['parent_id'], unique=False)
    op.create_table('files',
    sa.Column('blob_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['file_blobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['folder_id'], ['file_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_blob_id'), 'files', ['blob_id'], unique=False)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_index('ix_files_owner_blob', 'files', ['owner_user_id', 'blob_id'], unique=False)
    op.create_index(op.f('ix_files_owner_user_id'), 'files', ['owner_user_id'], unique=False)
    op.create_table('file_usages',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'entity_type', 'entity_id', name='uq_file_usage')
    )
    op.create_index('ix_file_usages_entity', 'file_usages', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_file_usages_file_id'), 'file_usages', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_usages_file_id'), table_name='file_usages')
    op.drop_index('ix_file_usages_entity', table_name='file_usages')
    op.drop_table('file_usages')
    op.drop_index(op.f('ix_files_owner_user_id'), table_name='files')
    op.drop_index('ix_files_owner_blob', table_name='files')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_blob_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_folders_parent_id'), table_name='file_folders')
    op.drop_index(op.f('ix_file_folders_owner_user_id'), table_name='file_folders')
    op.drop_table('file_folders')
    op.drop_index(op.f('ix_file_blobs_sha256'), table_name='file_blobs')
    op.drop_table('file_blobs')
    # ### end Alembic commands ###
