"""course_lms_lesson_resource

Revision ID: 5ce668fe2e49
Revises: f6d412727c60
Create Date: 2026-07-05 19:57:03.148742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce668fe2e49'
down_revision: Union[str, Sequence[str], None] = 'f6d412727c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('kafedra_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kafedra_id'], ['kafedras.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_specialities_kafedra_id'), 'specialities', ['kafedra_id'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('semester_number', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('kafedra_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kafedra_id'], ['kafedras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_academic_year_id'), 'courses', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_courses_faculty_id'), 'courses', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_courses_kafedra_id'), 'courses', ['kafedra_id'], unique=False)
    op.create_index(op.f('ix_courses_speciality_id'), 'courses', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_courses_subject_id'), 'courses', ['subject_id'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_table('course_groups',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'group_id', name='uq_course_group')
    )
    op.create_index(op.f('ix_course_groups_course_id'), 'course_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_groups_group_id'), 'course_groups', ['group_id'], unique=False)
    op.create_table('resources',
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_course_id'), 'resources', ['course_id'], unique=False)
    op.create_index(op.f('ix_resources_lesson_id'), 'resources', ['lesson_id'], unique=False)
    op.add_column('assignments', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_modules', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_foreign_key(None, 'course_modules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('groups', sa.Column('speciality_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_groups_speciality_id'), 'groups', ['speciality_id'], unique=False)
    op.create_foreign_key(None, 'groups', 'specialities', ['speciality_id'], ['id'], ondelete='SET NULL')
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    # NOTE: quizzes.semester_id / semesters.is_active are pre-existing, unrelated
    # schema drift (not touched by this migration) — intentionally excluded.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_column('lessons', 'course_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_speciality_id'), table_name='groups')
    op.drop_column('groups', 'speciality_id')
    op.drop_constraint(None, 'course_modules', type_='foreignkey')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_column('course_modules', 'course_id')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_column('assignments', 'course_id')
    op.drop_index(op.f('ix_resources_lesson_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_course_groups_group_id'), table_name='course_groups')
    op.drop_index(op.f('ix_course_groups_course_id'), table_name='course_groups')
    op.drop_table('course_groups')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_subject_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_speciality_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_kafedra_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_faculty_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_academic_year_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_specialities_kafedra_id'), table_name='specialities')
    op.drop_table('specialities')
    # ### end Alembic commands ###
