"""hemis_data_credentials

Revision ID: 66963d90b1a5
Revises: c8d2e5f6a310
Create Date: 2026-09-03 17:09:59.421767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66963d90b1a5'
down_revision: Union[str, Sequence[str], None] = 'c8d2e5f6a310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hemis_data_credentials',
    sa.Column('data_url', sa.String(length=255), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hemis_data_credentials')
    # ### end Alembic commands ###
