"""Adminning «yashirish» bayrogʻi

Beshta spravochnikka ``is_hidden`` qoʻshiladi. ``is_active`` dan alohida:
u EduPlan sinxronizatsiyasiniki va «manbada hali bormi» degan maʼnoni
bildiradi. Ikkovini bitta ustunga yigʻsak, sinxronizatsiya admin yashirgan
satrni qaytadan yoqib yuborardi.

Mavjud satrlar uchun default `false` — yaʼni hech nima yashirilmaydi va
migratsiya koʻrinishni oʻzgartirmaydi.


Revision ID: 8a1ef9064485
Revises: 4658ab2130d2
Create Date: 2026-09-01 06:23:07.034864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1ef9064485'
down_revision: Union[str, Sequence[str], None] = '4658ab2130d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('groups', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('kafedras', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('specialities', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('subjects', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'is_hidden')
    op.drop_column('specialities', 'is_hidden')
    op.drop_column('kafedras', 'is_hidden')
    op.drop_column('groups', 'is_hidden')
    op.drop_column('faculties', 'is_hidden')
    # ### end Alembic commands ###
