"""add semester isolation

Revision ID: abf2d4975379
Revises: e4b1f7c92a08
Create Date: 2026-06-15 04:48:12.971614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf2d4975379'
down_revision: Union[str, Sequence[str], None] = 'e4b1f7c92a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_syllabus_sinf'), 'syllabuses', type_='unique')
    op.drop_index(op.f('ix_syllabuses_sinf_id'), table_name='syllabuses')
    op.create_index(op.f('ix_syllabuses_sinf_id'), 'syllabuses', ['sinf_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabuses_sinf_id'), table_name='syllabuses')
    op.create_index(op.f('ix_syllabuses_sinf_id'), 'syllabuses', ['sinf_id'], unique=False)
    op.create_unique_constraint(op.f('uq_syllabus_sinf'), 'syllabuses', ['sinf_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
