"""Dars guruhi ixtiyoriy: bo'sh = kursning barcha guruhlari.

Kurs endi ma'ruza oqimiga tegishli — EPOS yuklamasidan yig'ilgan kurslarning
yarmida bir nechta guruh bor, eng kattasida to'qqizta. Har guruhga alohida
dars yozish o'qituvchini bir xil ishni to'qqiz marta qilishga majbur qilardi.

Mavjud satrlarga tegilmaydi: ularda guruh ko'rsatilgan va o'shanday qoladi.

Revision ID: c160a967832a
Revises: c9f9871380c2
Create Date: 2026-09-01 18:39:02.606957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c160a967832a'
down_revision: Union[str, Sequence[str], None] = 'c9f9871380c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Guruhsiz darslar paydo bo'lgan bo'lsa, orqaga qaytarish NOT NULL'da
    to'xtaydi — avval ularni o'chirish yoki guruh berish kerak.
    """
    op.alter_column('lessons', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
