"""Kursda bir nechta oʻqituvchi va avtomatik kurslar uchun kalit

Ikki narsa birga:

1. ``course_teachers`` — kursning oʻqituvchilari roʻyxati. Bitta asosiy
   (``role="main"``) va ixtiyoriy assistentlar. ``Course.teacher_id``
   qoldiriladi va «asosiy oʻqituvchi» maʼnosini oladi: u oltita joyda ruxsat
   kaliti sifatida ishlatiladi va uni bir vaqtda olib tashlash hammasini
   buzardi.

2. ``courses`` ga koʻzgu ustunlari. EPOS'da kurs degan obyekt yoʻq, shuning
   uchun avtomatik yaratilgan kursning ``external_id`` si oʻzimiz tomonidan
   yigʻiladi. Usiz takroriy progn oʻsha kurslarni qaytadan yaratardi va
   qoʻlda tuzilganini avtomatikdan ajratib boʻlmasdi.

Mavjud kurslarning egasi yangi jadvalga koʻchiriladi — aks holda ular
oʻqituvchisiz qolib, roʻyxat toʻliq boʻlmasdi.


Revision ID: c9f9871380c2
Revises: 060ef70e266f
Create Date: 2026-09-01 16:19:48.738766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f9871380c2'
down_revision: Union[str, Sequence[str], None] = '060ef70e266f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_teachers',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_teacher')
    )
    op.create_index(op.f('ix_course_teachers_course_id'), 'course_teachers', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_teachers_user_id'), 'course_teachers', ['user_id'], unique=False)
    op.add_column('courses', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('courses', sa.Column('external_source', sa.String(length=32), nullable=True))
    op.add_column('courses', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index('uq_courses_external_ref', 'courses', ['external_source', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###

    # Mavjud kurslarning egasini roʻyxatga koʻchiramiz: jadval toʻliq boʻlishi
    # kerak, aks holda «kursning oʻqituvchilari» degan savolga ikki manbadan
    # javob berishga toʻgʻri kelardi.
    op.execute(
        """
        INSERT INTO course_teachers (course_id, user_id, role, created_at, updated_at)
        SELECT id, teacher_id, 'main', now(), now()
        FROM courses
        WHERE teacher_id IS NOT NULL
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_courses_external_ref', table_name='courses', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('courses', 'is_active')
    op.drop_column('courses', 'synced_at')
    op.drop_column('courses', 'external_source')
    op.drop_column('courses', 'external_id')
    op.drop_index(op.f('ix_course_teachers_user_id'), table_name='course_teachers')
    op.drop_index(op.f('ix_course_teachers_course_id'), table_name='course_teachers')
    op.drop_table('course_teachers')
    # ### end Alembic commands ###
