"""Xizmat fani va testning koʻp guruhi

Ikki oʻzgarish:

* `subjects.is_countable` — test uchun tuzilgan xizmat fani hisob-kitobga
  kirmasligi uchun. Standart `true`, yaʼni mavjud fanlar oʻzgarmaydi;
* `quiz_groups` — bitta testni bir necha guruhga biriktirish. Mavjud
  testlarning `quizzes.group_id` qiymati shu jadvalga koʻchiriladi,
  ustunning oʻzi joyida qoladi (unga kodning koʻp joyi tayanadi).

Revision ID: d87b5280e061
Revises: 207e0c71cd8f
Create Date: 2026-09-30 10:03:41.892982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87b5280e061'
down_revision: Union[str, Sequence[str], None] = '207e0c71cd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_groups',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'group_id', name='uq_quiz_group')
    )
    op.create_index(op.f('ix_quiz_groups_group_id'), 'quiz_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_quiz_groups_quiz_id'), 'quiz_groups', ['quiz_id'], unique=False)
    op.add_column('subjects', sa.Column('is_countable', sa.Boolean(), server_default='true', nullable=False))

    # Mavjud testlarning guruhi yangi jadvalga koʻchiriladi: usiz ular
    # «guruhsiz» boʻlib qolardi va talabalar kira olmasdi.
    op.execute(
        """
        INSERT INTO quiz_groups (quiz_id, group_id, created_at, updated_at)
        SELECT id, group_id, now(), now() FROM quizzes WHERE group_id IS NOT NULL
        ON CONFLICT (quiz_id, group_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'is_countable')
    op.drop_index(op.f('ix_quiz_groups_quiz_id'), table_name='quiz_groups')
    op.drop_index(op.f('ix_quiz_groups_group_id'), table_name='quiz_groups')
    op.drop_table('quiz_groups')
    # ### end Alembic commands ###
