"""hemis_last_student_sync_at

Revision ID: fc0cf636df71
Revises: 66963d90b1a5
Create Date: 2026-09-03 17:28:33.794522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0cf636df71'
down_revision: Union[str, Sequence[str], None] = '66963d90b1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hemis_data_credentials', sa.Column('last_student_sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hemis_data_credentials', 'last_student_sync_at')
    # ### end Alembic commands ###
