"""structure_display_columns_curriculum_and_pii

Revision ID: fec332bffb52
Revises: c8a3f0d2e517
Create Date: 2026-07-29 06:38:15.279343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec332bffb52'
down_revision: Union[str, Sequence[str], None] = 'c8a3f0d2e517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speciality_id', 'subject_id', 'semester', name='idx_unique_curriculum_row')
    )
    op.create_index(op.f('ix_curriculum_speciality_id'), 'curriculum', ['speciality_id'], unique=False)
    op.create_index(op.f('ix_curriculum_subject_id'), 'curriculum', ['subject_id'], unique=False)
    op.create_index(op.f('ix_curriculum_teacher_user_id'), 'curriculum', ['teacher_user_id'], unique=False)
    op.add_column('employees', sa.Column('position_title', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('work_email', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('work_phone', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=8), nullable=True))
    op.add_column('employees', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(length=16), server_default='Faol', nullable=False))
    op.add_column('employees', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('jshshir', sa.String(length=14), nullable=True))
    op.add_column('employees', sa.Column('passport', sa.String(length=16), nullable=True))
    op.add_column('employees', sa.Column('personal_phone', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('faculties', sa.Column('code', sa.String(length=16), nullable=True))
    op.add_column('faculties', sa.Column('dekan_user_id', sa.Integer(), nullable=True))
    op.add_column('faculties', sa.Column('dekan_name', sa.String(length=255), nullable=True))
    op.add_column('faculties', sa.Column('color_bg', sa.String(length=9), nullable=True))
    op.add_column('faculties', sa.Column('color_fg', sa.String(length=9), nullable=True))
    op.add_column('faculties', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_faculties_dekan_user_id'), 'faculties', ['dekan_user_id'], unique=False)
    op.create_foreign_key(
        'fk_faculties_dekan_user_id_users', 'faculties', 'users', ['dekan_user_id'], ['id'],
        ondelete='SET NULL',
    )
    op.add_column('groups', sa.Column('kurs', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('sardor_student_id', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_groups_sardor_student_id'), 'groups', ['sardor_student_id'], unique=False)
    op.create_foreign_key(
        'fk_groups_sardor_student_id_students', 'groups', 'students', ['sardor_student_id'], ['id'],
        ondelete='SET NULL',
    )
    op.add_column('kafedras', sa.Column('mudir_user_id', sa.Integer(), nullable=True))
    op.add_column('kafedras', sa.Column('mudir_name', sa.String(length=255), nullable=True))
    op.add_column('kafedras', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_kafedras_mudir_user_id'), 'kafedras', ['mudir_user_id'], unique=False)
    op.create_foreign_key(
        'fk_kafedras_mudir_user_id_users', 'kafedras', 'users', ['mudir_user_id'], ['id'],
        ondelete='SET NULL',
    )
    op.add_column('specialities', sa.Column('code', sa.String(length=16), nullable=True))
    op.add_column('specialities', sa.Column('education_form', sa.String(length=32), nullable=True))
    op.add_column('specialities', sa.Column('academic_year', sa.String(length=16), nullable=True))
    op.add_column('specialities', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.add_column('students', sa.Column('jshshir', sa.String(length=14), nullable=True))
    op.add_column('students', sa.Column('passport', sa.String(length=16), nullable=True))
    op.add_column('students', sa.Column('region', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('district', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('social_category', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('benefit', sa.String(length=64), nullable=True))
    op.add_column('subjects', sa.Column('kafedra_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('code', sa.String(length=32), nullable=True))
    op.add_column('subjects', sa.Column('credit', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_subjects_kafedra_id'), 'subjects', ['kafedra_id'], unique=False)
    op.create_foreign_key(
        'fk_subjects_kafedra_id_kafedras', 'subjects', 'kafedras', ['kafedra_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # Разовый бэкфилл порядка. Со server_default='0' все существующие строки
    # получили бы одинаковый position, и сортировка по нему стала бы
    # недетерминированной: дерево структуры при каждом запросе выглядело бы
    # иначе. Раскладываем по id — это тот порядок, в котором записи заводили.
    for table in ('faculties', 'kafedras', 'specialities', 'groups'):
        op.execute(f'UPDATE {table} SET position = id')

    # Названия факультетов и фанов до сих пор приводились к нижнему регистру
    # при создании — валидатор в схемах это делал. В новом интерфейсе они
    # выводятся как есть, и «konchilik fakulteti» читается как опечатка.
    # Поднимаем только первую букву: initcap() испортил бы аббревиатуры
    # («IT fakulteti» → «It Fakulteti»).
    for table in ('faculties', 'subjects'):
        op.execute(
            f"UPDATE {table} "
            f"SET name = upper(left(name, 1)) || substr(name, 2) "
            f"WHERE name <> upper(left(name, 1)) || substr(name, 2)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_subjects_kafedra_id_kafedras', 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_kafedra_id'), table_name='subjects')
    op.drop_column('subjects', 'description')
    op.drop_column('subjects', 'semester')
    op.drop_column('subjects', 'credit')
    op.drop_column('subjects', 'code')
    op.drop_column('subjects', 'kafedra_id')
    op.drop_column('students', 'benefit')
    op.drop_column('students', 'social_category')
    op.drop_column('students', 'district')
    op.drop_column('students', 'region')
    op.drop_column('students', 'passport')
    op.drop_column('students', 'jshshir')
    op.drop_column('specialities', 'position')
    op.drop_column('specialities', 'academic_year')
    op.drop_column('specialities', 'education_form')
    op.drop_column('specialities', 'code')
    op.drop_constraint('fk_kafedras_mudir_user_id_users', 'kafedras', type_='foreignkey')
    op.drop_index(op.f('ix_kafedras_mudir_user_id'), table_name='kafedras')
    op.drop_column('kafedras', 'position')
    op.drop_column('kafedras', 'mudir_name')
    op.drop_column('kafedras', 'mudir_user_id')
    op.drop_constraint('fk_groups_sardor_student_id_students', 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_sardor_student_id'), table_name='groups')
    op.drop_column('groups', 'position')
    op.drop_column('groups', 'sardor_student_id')
    op.drop_column('groups', 'kurs')
    op.drop_constraint('fk_faculties_dekan_user_id_users', 'faculties', type_='foreignkey')
    op.drop_index(op.f('ix_faculties_dekan_user_id'), table_name='faculties')
    op.drop_column('faculties', 'position')
    op.drop_column('faculties', 'color_fg')
    op.drop_column('faculties', 'color_bg')
    op.drop_column('faculties', 'dekan_name')
    op.drop_column('faculties', 'dekan_user_id')
    op.drop_column('faculties', 'code')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'personal_phone')
    op.drop_column('employees', 'passport')
    op.drop_column('employees', 'jshshir')
    op.drop_column('employees', 'last_login_at')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'birth_date')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'work_phone')
    op.drop_column('employees', 'work_email')
    op.drop_column('employees', 'position_title')
    op.drop_index(op.f('ix_curriculum_teacher_user_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_subject_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_speciality_id'), table_name='curriculum')
    op.drop_table('curriculum')
    # ### end Alembic commands ###
